name: Daily Script Execution

on:
  schedule:
    - cron: "15 0 * * *"  # Runs at midnight every day
  workflow_dispatch:     # Allows manual triggering of the workflow

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.4'  # Replace with your Python version if needed
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  
    - name: Download NLTK Data
      run: |
        python -m nltk.downloader stopwords
    - name: Run script
      run: python main.py
